# Generated by Django 2.2.6 on 2019-12-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymnasium', '0002_auto_20191227_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmenttypes',
            options={},
        ),
    ]
