# Generated by Django 2.2.6 on 2019-12-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymnasium', '0003_auto_20191227_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquipmentTypes',
            new_name='Equipmenttype',
        ),
    ]
