# Generated by Django 2.2.6 on 2019-12-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymnasium', '0004_auto_20191227_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
