# Generated by Django 2.2.6 on 2019-12-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='equipment_interest',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='package_interest',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
