# Generated by Django 2.2.6 on 2020-04-05 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymnasium', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='trainer',
            field=models.ForeignKey(limit_choices_to={'is_trainer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to=settings.AUTH_USER_MODEL),
        ),
    ]
