# Generated by Django 2.2.6 on 2020-04-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymnasium', '0005_auto_20200405_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='end_time',
            field=models.DateField(verbose_name='Expiry for Notification'),
        ),
    ]
