# Generated by Django 2.2.6 on 2020-04-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymnasium', '0006_auto_20200405_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='end_time',
            new_name='end_date',
        ),
    ]
