# Generated by Django 2.2.6 on 2020-04-05 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymnasium', '0007_auto_20200405_1338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
