# Generated by Django 2.2.6 on 2020-04-07 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymnasium', '0009_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='package',
        ),
        migrations.RemoveField(
            model_name='package',
            name='timings',
        ),
        migrations.AlterField(
            model_name='membership',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_for_membership', to='gymnasium.Package'),
        ),
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('timings', models.CharField(max_length=100)),
                ('package_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_for_class', to='gymnasium.Package')),
            ],
            options={
                'verbose_name': 'Gym class',
                'verbose_name_plural': 'Gym classes',
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='gym_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='gym_class_for_membership', to='gymnasium.GymClass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='gym_class',
            field=models.ManyToManyField(related_name='gym_class_for_notification', to='gymnasium.GymClass'),
        ),
    ]
