# Generated by Django 2.2.6 on 2020-04-08 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymnasium', '0010_auto_20200407_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymnasium.Equipmenttype'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
