# Generated by Django 2.2.6 on 2020-04-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200405_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='mobile',
            field=models.IntegerField(default=9999999999),
            preserve_default=False,
        ),
    ]
